# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtsvn.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_centralWidget = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_centralWidget.setObjectName("gridLayout_centralWidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_repos = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_repos.sizePolicy().hasHeightForWidth())
        self.groupBox_repos.setSizePolicy(sizePolicy)
        self.groupBox_repos.setObjectName("groupBox_repos")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_repos)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_repos = QtWidgets.QListWidget(self.groupBox_repos)
        self.listWidget_repos.setMinimumSize(QtCore.QSize(100, 0))
        self.listWidget_repos.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.listWidget_repos.setObjectName("listWidget_repos")
        self.verticalLayout.addWidget(self.listWidget_repos)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_repoConfig = QtWidgets.QWidget()
        self.tab_repoConfig.setObjectName("tab_repoConfig")
        self.gridLayout_tabConfig = QtWidgets.QGridLayout(self.tab_repoConfig)
        self.gridLayout_tabConfig.setObjectName("gridLayout_tabConfig")
        self.groupBox_login = QtWidgets.QGroupBox(self.tab_repoConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_login.sizePolicy().hasHeightForWidth())
        self.groupBox_login.setSizePolicy(sizePolicy)
        self.groupBox_login.setFlat(False)
        self.groupBox_login.setObjectName("groupBox_login")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_login)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_configssh = QtWidgets.QCheckBox(self.groupBox_login)
        self.checkBox_configssh.setChecked(True)
        self.checkBox_configssh.setObjectName("checkBox_configssh")
        self.gridLayout.addWidget(self.checkBox_configssh, 2, 2, 1, 2)
        self.lineEdit_alias = QtWidgets.QLineEdit(self.groupBox_login)
        self.lineEdit_alias.setObjectName("lineEdit_alias")
        self.gridLayout.addWidget(self.lineEdit_alias, 2, 1, 1, 1)
        self.tabWidget_login = QtWidgets.QTabWidget(self.groupBox_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_login.sizePolicy().hasHeightForWidth())
        self.tabWidget_login.setSizePolicy(sizePolicy)
        self.tabWidget_login.setObjectName("tabWidget_login")
        self.tab_password = QtWidgets.QWidget()
        self.tab_password.setObjectName("tab_password")
        self.horizontalLayout_tabPassword = QtWidgets.QHBoxLayout(self.tab_password)
        self.horizontalLayout_tabPassword.setObjectName("horizontalLayout_tabPassword")
        self.label_password = QtWidgets.QLabel(self.tab_password)
        self.label_password.setWordWrap(False)
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_tabPassword.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(self.tab_password)
        self.lineEdit_password.setInputMask("")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_tabPassword.addWidget(self.lineEdit_password)
        self.pushButton_loginPassword = QtWidgets.QPushButton(self.tab_password)
        self.pushButton_loginPassword.setObjectName("pushButton_loginPassword")
        self.horizontalLayout_tabPassword.addWidget(self.pushButton_loginPassword)
        self.tabWidget_login.addTab(self.tab_password, "")
        self.tab_sshkey = QtWidgets.QWidget()
        self.tab_sshkey.setObjectName("tab_sshkey")
        self.horizontalLayout_tabSshkey = QtWidgets.QHBoxLayout(self.tab_sshkey)
        self.horizontalLayout_tabSshkey.setObjectName("horizontalLayout_tabSshkey")
        self.label_sshkey = QtWidgets.QLabel(self.tab_sshkey)
        self.label_sshkey.setObjectName("label_sshkey")
        self.horizontalLayout_tabSshkey.addWidget(self.label_sshkey)
        self.lineEdit_sshkey = QtWidgets.QLineEdit(self.tab_sshkey)
        self.lineEdit_sshkey.setObjectName("lineEdit_sshkey")
        self.horizontalLayout_tabSshkey.addWidget(self.lineEdit_sshkey)
        self.pushButton_loadKey = QtWidgets.QPushButton(self.tab_sshkey)
        self.pushButton_loadKey.setObjectName("pushButton_loadKey")
        self.horizontalLayout_tabSshkey.addWidget(self.pushButton_loadKey)
        self.pushButton_loginKey = QtWidgets.QPushButton(self.tab_sshkey)
        self.pushButton_loginKey.setObjectName("pushButton_loginKey")
        self.horizontalLayout_tabSshkey.addWidget(self.pushButton_loginKey)
        self.tabWidget_login.addTab(self.tab_sshkey, "")
        self.gridLayout.addWidget(self.tabWidget_login, 3, 0, 1, 4)
        self.lineEdit_address = QtWidgets.QLineEdit(self.groupBox_login)
        self.lineEdit_address.setText("")
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.gridLayout.addWidget(self.lineEdit_address, 1, 1, 1, 3)
        self.label_alias = QtWidgets.QLabel(self.groupBox_login)
        self.label_alias.setObjectName("label_alias")
        self.gridLayout.addWidget(self.label_alias, 2, 0, 1, 1)
        self.label_address = QtWidgets.QLabel(self.groupBox_login)
        self.label_address.setObjectName("label_address")
        self.gridLayout.addWidget(self.label_address, 1, 0, 1, 1)
        self.label_username = QtWidgets.QLabel(self.groupBox_login)
        self.label_username.setObjectName("label_username")
        self.gridLayout.addWidget(self.label_username, 0, 0, 1, 1)
        self.label_logo = QtWidgets.QLabel(self.groupBox_login)
        self.label_logo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_logo.setObjectName("label_logo")
        self.gridLayout.addWidget(self.label_logo, 0, 2, 1, 1)
        self.comboBox_logo = QtWidgets.QComboBox(self.groupBox_login)
        self.comboBox_logo.setObjectName("comboBox_logo")
        self.gridLayout.addWidget(self.comboBox_logo, 0, 3, 1, 1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.groupBox_login)
        self.lineEdit_username.setInputMask("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout.addWidget(self.lineEdit_username, 0, 1, 1, 1)
        self.gridLayout_tabConfig.addWidget(self.groupBox_login, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_repoConfig, "")
        self.tab_remoteSvn = QtWidgets.QWidget()
        self.tab_remoteSvn.setObjectName("tab_remoteSvn")
        self.verticalLayout_remoteSvn = QtWidgets.QVBoxLayout(self.tab_remoteSvn)
        self.verticalLayout_remoteSvn.setObjectName("verticalLayout_remoteSvn")
        self.label_remotePath = QtWidgets.QLabel(self.tab_remoteSvn)
        self.label_remotePath.setObjectName("label_remotePath")
        self.verticalLayout_remoteSvn.addWidget(self.label_remotePath)
        self.treeView_remoteSvn = QtWidgets.QTreeView(self.tab_remoteSvn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_remoteSvn.sizePolicy().hasHeightForWidth())
        self.treeView_remoteSvn.setSizePolicy(sizePolicy)
        self.treeView_remoteSvn.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeView_remoteSvn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeView_remoteSvn.setAutoScrollMargin(16)
        self.treeView_remoteSvn.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.treeView_remoteSvn.setIndentation(20)
        self.treeView_remoteSvn.setObjectName("treeView_remoteSvn")
        self.treeView_remoteSvn.header().setCascadingSectionResizes(False)
        self.treeView_remoteSvn.header().setDefaultSectionSize(100)
        self.treeView_remoteSvn.header().setMinimumSectionSize(60)
        self.treeView_remoteSvn.header().setStretchLastSection(True)
        self.verticalLayout_remoteSvn.addWidget(self.treeView_remoteSvn)
        self.tabWidget.addTab(self.tab_remoteSvn, "")
        self.tab_localSvn = QtWidgets.QWidget()
        self.tab_localSvn.setObjectName("tab_localSvn")
        self.verticalLayout_localSvn = QtWidgets.QVBoxLayout(self.tab_localSvn)
        self.verticalLayout_localSvn.setObjectName("verticalLayout_localSvn")
        self.comboBox_localCos = QtWidgets.QComboBox(self.tab_localSvn)
        self.comboBox_localCos.setObjectName("comboBox_localCos")
        self.verticalLayout_localSvn.addWidget(self.comboBox_localCos)
        self.label_localCos = QtWidgets.QLabel(self.tab_localSvn)
        self.label_localCos.setObjectName("label_localCos")
        self.verticalLayout_localSvn.addWidget(self.label_localCos)
        self.treeView_localSvn = QtWidgets.QTreeView(self.tab_localSvn)
        self.treeView_localSvn.setObjectName("treeView_localSvn")
        self.verticalLayout_localSvn.addWidget(self.treeView_localSvn)
        self.tabWidget.addTab(self.tab_localSvn, "")
        self.tab_verionCtrl = QtWidgets.QWidget()
        self.tab_verionCtrl.setObjectName("tab_verionCtrl")
        self.tabWidget.addTab(self.tab_verionCtrl, "")
        self.gridLayout_centralWidget.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_login.setCurrentIndex(0)
        self.comboBox_logo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SalVatioN"))
        self.groupBox_repos.setTitle(_translate("MainWindow", "Bundle List"))
        self.groupBox_login.setTitle(_translate("MainWindow", "Repo Configuration"))
        self.checkBox_configssh.setText(_translate("MainWindow", "Auto-config sshkey"))
        self.label_password.setText(_translate("MainWindow", "Password:"))
        self.pushButton_loginPassword.setText(_translate("MainWindow", "Save"))
        self.tabWidget_login.setTabText(self.tabWidget_login.indexOf(self.tab_password), _translate("MainWindow", "Via Password"))
        self.label_sshkey.setText(_translate("MainWindow", "SSH-Key:"))
        self.pushButton_loadKey.setText(_translate("MainWindow", "Load"))
        self.pushButton_loginKey.setText(_translate("MainWindow", "Save"))
        self.tabWidget_login.setTabText(self.tabWidget_login.indexOf(self.tab_sshkey), _translate("MainWindow", "Via SSH-Key"))
        self.label_alias.setText(_translate("MainWindow", "Identifier:"))
        self.label_address.setText(_translate("MainWindow", "Address:"))
        self.label_username.setText(_translate("MainWindow", "Username:"))
        self.label_logo.setText(_translate("MainWindow", "Logo:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_repoConfig), _translate("MainWindow", "Repo Cofigure"))
        self.label_remotePath.setText(_translate("MainWindow", "[Root]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_remoteSvn), _translate("MainWindow", "Remote View"))
        self.label_localCos.setText(_translate("MainWindow", "Local Checkouts:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_localSvn), _translate("MainWindow", "Local Checkout"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_verionCtrl), _translate("MainWindow", "Version Control"))

